rvm: 2.1.3
language: objective-c
before_script:
- brew update
- brew outdated xctool || brew upgrade xctool
script:
- xctool -project CGOperator.xcodeproj -scheme CGOperator -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -reporter pretty
- xcodebuild -project CGOperator.xcodeproj -scheme CGOperator -destination 'platform=iOS Simulator,name=iPhone 6' test | xcpretty -c && exit ${PIPESTATUS[0]}

